# Generated by Django 4.1.5 on 2023-01-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name=''),
        ),
    ]
